### PR TITLE
Docs for OS X

### LINKED ISSUE #276: Better installation instructions
Since the same issues keep popping up again and again ( #270 #275 #219 #261 ), it seems like we must have some shortcomings in the documentation.

In particular, the following points should be addressed explicitly:

- audioread backends
- scikit-samplerate
- general installation issues on osx / pointers to anaconda install instructions

Does anyone out there, preferably a mac user with direct experience, want to chip in on this?

### PR DESCRIPTION
**Pull request by stefan-balke**
Fixes #276

### CODE REVIEW

**Comment by bmcfee** [comment]
This looks great so far, thanks!

Can we also include this as a topic in the documentation, rather than (in addition to?) the readme?

Also, do we really recommend using brew?  Most people I've talked to recommend using (ana)conda for managing python environments.  Unless you're talking about using brew only for libsamplerate, in which case, the docs should be more explicit on that point.

**Comment by stefan-balke** [comment]
I personally use brew for my Python setup but this is more a matter of taste.
Anaconda is fine, too.
If many people use this, we might add `conda install` to `pip install`?

**Comment by bmcfee** [comment]
> If many people use this, we might add conda install to pip install?

See #202 :)  So.. not yet.

The problem here is that there aren't conda distributions for libsamplerate or ffmpeg.  (ffmpeg should be a last-ditch backend though; gstreamer is a much better option since it doesn't invoke a shell.)

**Comment by bmcfee** [comment]
Is there anything left to do on this one, or is it merge-ready?

**Comment by stefan-balke** [comment]
I think as long as Anaconda is not compatible with all dependencies - this is good for now.

**Comment by bmcfee** [comment]
Ok.  I'll punt other updates into #202 and merge this one then.

Thanks again!

**Pull request merged**
