### PR TITLE
CQT Tests

### PR DESCRIPTION
**Pull request by ebattenberg**
I started writing the tests I promised in #150.  Right now it's mostly boilerplate.  I will update in my free moments this week.   What I plan to focus other than just code coverage is approximate equivalence between the different efficiency optimizations.   Let me know if you have any ideas for other things to test.

### CODE REVIEW

**Comment by bmcfee** [comment]
> What I plan to focus other than just code coverage is approximate equivalence between the different efficiency optimizations.

Sounds great!  Thanks for doing this.

**Comment by bmcfee** [comment]
I guess we actually need to fix the samplerate dependency on travis before the preemptive downsampling code can be tested, right?

At present, it installs through apt, but scikits.samplerate can't find it.

**Comment by ebattenberg** [comment]
> I guess we actually need to fix the samplerate dependency on travis before the preemptive downsampling code can be tested, right?

Yup.  The tests are passing over here so far when I run them on my end.  (with samplerate installed).

**Comment by ebattenberg** [comment]
And it looks like libsamplerate0-dev is the one I installed to get it working on my machine.  That's the one travis is apt-getting.  Hmm.

**Comment by bmcfee** [comment]
Yeah, same on my end.  I blame the dogpile of package managers, in order of dumbness (apt, pip, conda)...

**Comment by ebattenberg** [comment]
Other topic:  The tests helped me find a gnarly bug that breaks the early downsampling if `n_bins < bins_per_octave`.  I'm thinking we should support that use case even though it would be uncommon.  What are your thoughts?

**Comment by bmcfee** [comment]
> n_bins < bins_per_octave. I'm thinking we should support that use case even though it would be uncommon

Sure.  I don't see any reason not to support generating cqt's that are less than one octave high.

**Comment by ebattenberg** [comment]
> Sure. I don't see any reason not to support generating cqt's that are less than one octave high.

Also, this isn't exactly specific to the early downsampling.  It's just more apparent because we're hanging out near Nyquist more often because of it.  If you wanted a CQT with an `fmin` near enough to Nyquist that a whole octave won't fit, then you'll run into problems because `__fft_filters` always generates an entire octave of filters even if they aren't used.

**Comment by bmcfee** [comment]
> Yeah, same on my end. I blame the dogpile of package managers, in order of dumbness (apt, pip, conda)...

I took another stab at trying to fix this, but no dice.  pip installs samplerate happily, and then the conda environment breaks things.

**Comment by bmcfee** [comment]
After way too much prodding, I think this samplerate/conda issue can be resolved by hacking a custom numpy site.cfg for travis.  I'll take a crack at this later today; this note is mainly to myself.

**Comment by bmcfee** [comment]
Building samplerate from source within conda seems to work, but only on python2: https://travis-ci.org/bmcfee/travis_test/builds/53989101

This should be fixed by [this PR](https://github.com/cournape/samplerate/pull/5), but it's not yet integrated in pypi.

**Comment by bmcfee** [comment]
> This should be fixed by this PR, but it's not yet integrated in pypi.

indeed, this fixes it.

It seems unlikely that that PR will be merged any time soon, given the staleness of sksamplerate in pypi right now.  (Maybe we should encourage a proper fork?)

However, for testing, I think we can safely follow the build scheme in my test repo.

**Comment by bmcfee** [comment]
samplerate tests now work on travis: https://coveralls.io/builds/2094075

**Comment by ebattenberg** [comment]
Ok, I'm back on this.  Will try to get some passing tests written today.

**Comment by bmcfee** [comment]
I'm digging through this one again, and it seems like the tests that should pass are failing due to too much early downsampling.

The first iteration of the grid sweep gives a parameter set like
```python
test_constantq.test_cqt(array([ 1.,  0.,  0., ...,  0.,  0.,  0.]), 11025, 512, None, 1, 12, 0, 1, None, 1, 0.01)
```
which should make one bin at 'C2'.  In doing so, it creates a full 12-bin filter bank with the following frequencies:
```
[ 32.70319566  34.64782887  36.70809599  38.89087297  41.20344461
  43.65352893  46.24930284  48.9994295   51.9130872   55.          58.27047019
  61.73541266]
```
and an early-downsampled `sr=86.1328125`.

Maybe we need to explicitly handle the case where `bins_per_octave < n_bins`  to avoid this sort of thing?

**Comment by bmcfee** [comment]
Additionally, [this part](https://github.com/bmcfee/librosa/blob/develop/librosa/core/constantq.py#L453-L454) might be responsible, since it's forcing `filters.constant_q` to generate more filters than it needs.

**Comment by ebattenberg** [comment]
Yeah. I'm aware. Just haven't had time to insert the logic.

**Comment by bmcfee** [comment]
No problem.  I've pushed a couple of updates to this PR in https://github.com/bmcfee/librosa/tree/ebattenberg-cqt-tests , including the `n_filters` fix 9f5665cdbcafb5eb0c3c357081eb1766800c1e75 .

There's still something going wrong in computing the filter cutoff.  The Q factors within `cqt()` and `filters.constant_q` disagree substantially.  Not sure what's going on there...

**Comment by ebattenberg** [comment]
FWIW, I'm hoping to start using this stuff in some of my work in the next
week, so hopefully I'll have an excuse to spend some more time on it and
finally get the tests passing. But I know I've promised that for a while. :)

**Comment by bmcfee** [comment]
Coming back to this again.  It looks like early_downsampling is still being too aggressive.

I reduced the downsampling count calculation by 1, and this fixes most of our (currently failing) test cases.

**Comment by bmcfee** [comment]
Also, my previous hack 9f5665c introduced a bug in the filter length calculation, since it uses `bins_per_octave` to decide how to space the filters.  Oops!

**Comment by bmcfee** [comment]
> What I plan to focus other than just code coverage is approximate equivalence between the different efficiency optimizations. Let me know if you have any ideas for other things to test.

#196 contains bugfixes and tests for:

* error checking, size correctness
* approximate equivalence between cqt and hybrid_cqt (which implies pseudo_cqt)
* a simple "correctness" test where a pure tone is generated and recovered as a salient peak of the cqt, while ensuring that all incorrect frequency bins have sufficiently small magnitude.

Aside from filterbank construction (which is tested elsewhere), I think there's not much else to add here.  @ebattenberg : if this all sounds good, I'll close this PR and merge #196.

**Pull request merged**
