### PR TITLE
Frequency ticks

### PR DESCRIPTION
**Pull request by bmcfee**
Implements #291

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/bmcfee/librosa/pull/295" target="_blank">ReviewNinja

**Comment by bmcfee** [comment]
This one probably isn't merge-able until we reimplement the display tests in #284 .

In order to preserve the previous default behavior, I added a `freq_fmt` parameter to `specshow` that gets passed through to `frequency_ticks`.  Should a similar parameter be added to override time ticks?

**Comment by bmcfee** [comment]
#284 is resolved now, so this PR is no longer blocked.

The tests currently fail because the frequency ticks now include additional precision (eg, ``11025.00`` instead of ``11025``).

The added precision seems like clutter most of the time, at least with linear frequency axes.  As @drepetto mentioned in the thread [here](https://github.com/bmcfee/librosa/issues/291#issuecomment-165489518), it may only make sense to use scientific notation where appropriate, and keep integer formatting otherwise.  Anyone care to suggest a sensible policy for this?

**Comment by drepetto** [comment]
It seems like you'd only need fractional frequency labels when you have a pretty small frequency range, right? Maybe there's some clever way of using the ratio of display pixels to frequency bands or something to decide. 

And, of course, if you display frequencies < 1.0 then the fractional part should always be turned on.

Or it could just all be controlled by a couple flags (fractional, scientific). I don't know if flag proliferation is a problem or not...

best,
douglas

**Comment by dpwe** [comment]
Doesn't replacing the `{:0.2f}` with `{:.4g}` give us pretty much what we want?  Suppresses trailing zeros and decimal points, switches to scientific notation for numbers that are too big.
```
>>> for case in [0.00000012345, 0.00012345, 0.12345, 12.345, 123.450, 1234.5678, 12345.6, 123456]:
...   print "{:.4g}".format(case)
... 
1.235e-07
0.0001234
0.1235
12.35
123.5
1235
1.235e+04
1.235e+05
```

**Comment by drepetto** [comment]
Dan,

that sorta works, except that it'll make the most common plot frequency plot ranges, like 0-22050Hz, pretty ugly, since it switches to scientific notation at 10k. I think it makes sense to stay with one number format for an axis, no?

best,
douglas

**Comment by dpwe** [comment]
Shouldn't 0..22050 render as 0..22.05 kHz?

  DAn.

**Comment by bmcfee** [comment]
Thanks @dpwe , I had completely forgotten about the ``g`` format code.

This also revealed a bug/thinko in the frequency tickers where the ticks were forced to type ``int`` prior to display.  The latest commit fixes this (so that fractional ticks can occur) and uses `{:.5g}` as the default format.  Switching from 4 to 5 digits retains the expected formatting for commonly used nyquist frequencies (11025, 22050).

I've updated the test fixtures accordingly.



> I think it makes sense to stay with one number format for an axis, no?

I generally agree with that, except for when you have log axes, at which point scientific is the only thing that really makes sense.  Switching to g formatting here seems to do the right thing in the cases I've tried.  @drepetto how about you check out this PR branch, give it a spin, and let me know what you think?

**Comment by dpwe** [comment]
On Sun, Jan 31, 2016 at 9:02 AM, Brian McFee <notifications@github.com>
wrote:

> Thanks @dpwe <https://github.com/dpwe> , I had completely forgotten about
> the g format code.
>
Haha.  I spent half an hour trying to craft regexps that would delete
trailing zeros for strings that included a decimal point before I actually
checked the "format mini language" page.

  DAn.

**Comment by bmcfee** [comment]
Other to-do on this:

- [ ] full coverage on freq ticker test
- [ ] add analogous `time_fmt` option to display

**Comment by bmcfee** [comment]
I'm ready to stick a fork in this one, provided @drepetto is happy.

**Comment by bmcfee** [comment]
Gah! I did not mean to merge that already. Serves me right fit checking pr status on my phone.

**Comment by drepetto** [comment]
Okay, I'll take a look tonight. Thanks.

**Comment by drepetto** [comment]
Yep, works great now for the 1Hz data that started the thread. Thanks so much!

douglas

**Pull request merged**
